/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-background": "#131b2e",
        "primary-fixed": "#dbe1ff",
        "primary-container": "#2563eb",
        "on-primary-fixed-variant": "#003ea8",
        "outline-variant": "#c3c6d7",
        "surface-variant": "#dae2fd",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        "background": "#faf8ff",
        "secondary": "#006a61",
        "on-primary-container": "#eeefff",
        "inverse-on-surface": "#eef0ff",
        "on-tertiary": "#ffffff",
        "primary": "#004ac6",
        "surface-bright": "#faf8ff",
        "on-tertiary-container": "#f7edff",
        "error": "#ba1a1a",
        "tertiary-fixed": "#eaddff",
        "surface-container-high": "#e2e7ff",
        "on-secondary-container": "#006f66",
        "on-secondary-fixed": "#00201d",
        "inverse-primary": "#b4c5ff",
        "secondary-fixed-dim": "#6bd8cb",
        "surface-container-highest": "#dae2fd",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#eaedff",
        "tertiary-fixed-dim": "#d2bbff",
        "surface-tint": "#0053db",
        "outline": "#737686",
        "surface": "#faf8ff",
        "primary-fixed-dim": "#b4c5ff",
        "on-error-container": "#93000a",
        "surface-dim": "#d2d9f4",
        "secondary-fixed": "#89f5e7",
        "on-tertiary-fixed": "#25005a",
        "on-secondary": "#ffffff",
        "secondary-container": "#86f2e4",
        "on-surface": "#131b2e",
        "on-surface-variant": "#434655",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#5a00c6",
        "tertiary-container": "#8343f4",
        "on-secondary-fixed-variant": "#005049",
        "tertiary": "#6a1edb",
        "inverse-surface": "#283044",
        "on-primary-fixed": "#00174b",
        "surface-container-low": "#f2f3ff",

        // Dark tactical surface tokens used in Stitch dark command center layouts
        "cad-dark": "#0c0e14",
        "cad-panel": "#13161f",
        "cad-border": "#1e2230",
        "cad-accent": "#3b82f6"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px"
      },
      spacing: {
        "space-2xs": "0.125rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        gutter: "1rem",
        "gutter-desktop": "1.5rem",
        margin: "1rem",
        "margin-desktop": "2rem"
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        headline: ["Plus Jakarta Sans", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        "headline-xl": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "headline-sm": ["Plus Jakarta Sans"],
        "code-tabular": ["JetBrains Mono"],
        "label-sm": ["Inter"],
        "label-xs": ["Inter"],
        "label-md": ["Inter"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "body-sm": ["Inter"]
      },
      fontSize: {
        "headline-xl": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-lg": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-sm": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "code-tabular": ["13px", { lineHeight: "18px", fontWeight: "500" }],
        "label-md": ["13px", { lineHeight: "18px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "label-xs": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
